# Change these first
owner: k-hal # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE
